name: Build & Upload Snapshots (Gatsby)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  BUILD_ID: ${{ github.sha }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Gatsby site
        env:
          GATSBY_API_URL: ${{ secrets.API_URL }}
        run: |
          npm run build
          
      - name: Verify build
        run: |
          if [ ! -f public/index.html ]; then
            echo "Error: Build failed - index.html not found"
            exit 1
          fi
          echo "Build successful - found $(find public -name '*.html' | wc -l) HTML files"
          
      - name: Generate manifest
        run: |
          cat > public/manifest.json << EOF
          {
            "build_id": "${{ env.BUILD_ID }}",
            "domain": "${{ secrets.PRERENDER_DOMAIN }}",
            "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "route_count": $(find public -name '*.html' | wc -l),
            "routes": $(find public -name '*.html' -type f | sed 's|public||' | sed 's|/index.html|/|' | sed 's|.html||' | jq -R . | jq -s .),
            "trailingSlash": true,
            "basePath": "",
            "surrogate_key": "prerender-${{ secrets.PRERENDER_SITE_ID }}"
          }
          EOF
          
      - name: Upload snapshots to storage
        env:
          SNAPSHOT_TOKEN: ${{ secrets.PRERENDER_SNAPSHOT_TOKEN }}
          SITE_ID: ${{ secrets.PRERENDER_SITE_ID }}
          DOMAIN: ${{ secrets.PRERENDER_DOMAIN }}
        run: |
          # Package the public directory
          tar -czf public.tar.gz -C public .
          
          # Upload to platform
          curl -X POST https://api.prerenderhost.io/v1/upload \
            -H "Authorization: Bearer $SNAPSHOT_TOKEN" \
            -F "siteId=$SITE_ID" \
            -F "buildId=$BUILD_ID" \
            -F "files=@public.tar.gz"
          
      - name: Notify platform
        env:
          API_TOKEN: ${{ secrets.PRERENDER_API_TOKEN }}
          SITE_ID: ${{ secrets.PRERENDER_SITE_ID }}
        run: |
          ROUTE_COUNT=$(find public -name '*.html' | wc -l)
          
          curl -X POST https://api.prerenderhost.io/v1/builds/upload-complete \
            -H "Authorization: Bearer $API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "site_id": "'$SITE_ID'",
              "build_id": "'$BUILD_ID'",
              "route_count": '$ROUTE_COUNT'
            }'
